Repository mlee97/SOEN-343-Project-Team11, pull requests merged in 2020-12, with the labels that each got.

#58 Feat/#55/implement shh module
  smart-home-simulator/src/main/java/smarthomesimulator/DashboardController.java
  smart-home-simulator/src/main/java/smarthomesimulator/SmartHomeController.java
  smart-home-simulator/src/main/java/smarthomesimulator/model/Room.java
  smart-home-simulator/src/main/java/smarthomesimulator/model/Simulator.java
  smart-home-simulator/src/main/java/smarthomesimulator/model/Zone.java
  smart-home-simulator/src/main/resources/static/css/dashboard.css
  smart-home-simulator/src/main/resources/static/js/dashboard.js
  smart-home-simulator/src/main/resources/static/js/shhTab.js
  smart-home-simulator/src/main/webapp/WEB-INF/jsp/dashboard.jsp
Labels: Delivery #3

#59 Bug/56/display console output for shp
  smart-home-simulator/src/main/java/smarthomesimulator/DashboardController.java
  smart-home-simulator/src/main/java/smarthomesimulator/model/ConsoleOutput.java
  smart-home-simulator/src/main/java/smarthomesimulator/model/Simulator.java
  smart-home-simulator/src/main/resources/static/js/dashboard.js
  smart-home-simulator/src/main/webapp/WEB-INF/jsp/dashboard.jsp
Labels: Delivery #3, bug

#64 feat(61): Added operational clock
  smart-home-simulator/src/main/java/smarthomesimulator/DashboardController.java
  smart-home-simulator/src/main/resources/static/js/dashboard.js
  smart-home-simulator/src/main/webapp/WEB-INF/jsp/dashboard.jsp
Labels: Delivery #3, enhancement

#66 bug(#65): Update clock when context is modified
  smart-home-simulator/src/main/resources/static/js/dashboard.js
Labels: Delivery #3, bug

#72 feat(#68): Increase/Decrease Time over Time
  smart-home-simulator/src/main/java/smarthomesimulator/DashboardController.java
  smart-home-simulator/src/main/java/smarthomesimulator/model/Simulator.java
  smart-home-simulator/src/main/resources/static/js/dashboard.js
  smart-home-simulator/src/main/webapp/WEB-INF/jsp/SimulatorHome.jsp
  smart-home-simulator/src/main/webapp/WEB-INF/jsp/dashboard.jsp
Labels: Delivery #3, enhancement

#71 Fix away mode button not working as intended
  smart-home-simulator/src/main/java/smarthomesimulator/DashboardController.java
  smart-home-simulator/src/main/java/smarthomesimulator/model/Profile.java
  smart-home-simulator/src/main/java/smarthomesimulator/model/Room.java
  smart-home-simulator/src/main/java/smarthomesimulator/model/SHP.java
  smart-home-simulator/src/main/java/smarthomesimulator/model/Simulator.java
  smart-home-simulator/src/main/resources/static/js/dashboard.js
  smart-home-simulator/src/main/webapp/WEB-INF/jsp/dashboard.jsp
Labels: bug

#76 feat(#75): Added more console output for SHH
  smart-home-simulator/src/main/java/smarthomesimulator/DashboardController.java
  smart-home-simulator/src/main/resources/static/js/dashboard.js
Labels: Delivery #3, enhancement
